import express from 'express';
import dotenv from 'dotenv';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import { analyzeKdmInteraction } from './src/services/kdmConsistencyEngine';
import { loadKdmState, loadRecentKdmMemory, saveKdmInteraction, saveKntTrace, loadRecentKntTraces } from './src/services/kdmPersistenceService';
import { validateMemoryAgainstMessage } from './src/services/kairoMemoryConsistency';
import { validateKairoResponse } from './src/services/kairoResponseConsistency';
import { recordKdmMetric } from './src/services/kdmMetricsService';
import { computeKairoSpeechIdentity, speechIdentityPrompt } from './src/services/kairoSpeechIdentity';
import { applyRelationshipContext } from './src/services/relationshipBehaviorService';
import { tryLocalKairoReply } from './src/services/kairoLocalLanguageEngine';
import { languageMemorySummary } from './src/services/kairoLanguageMemory';
import type { DroitDynamicState, DroitPersonalityTraits } from './src/types/nexus';
dotenv.config();const app=express();const PORT=3000;app.use(express.json());let aiClient:GoogleGenAI|null=null;const now=()=>performance.now();const memoryCache=new Map<string,{expires:number,items:Array<{userMessage:string;reply:string}>}>(),MEMORY_TTL_MS=30000;const sleep=<T>(ms:number,value:T)=>new Promise<T>(resolve=>setTimeout(()=>resolve(value),ms));
function getGeminiClient(){if(!aiClient)aiClient=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY,httpOptions:{headers:{'User-Agent':'aistudio-build'}}});return aiClient}function extractOpenRouterText(data:any){const m=data?.choices?.[0]?.message,d=m?.content;if(typeof d==='string'&&d.trim())return d.trim();if(Array.isArray(d)){const j=d.map((p:any)=>typeof p==='string'?p:typeof p?.text==='string'?p.text:typeof p?.content==='string'?p.content:'').filter(Boolean).join('\n').trim();if(j)return j}return(typeof m?.text==='string'&&m.text.trim())?m.text.trim():(typeof data?.output_text==='string'?data.output_text.trim():'')}
async function callOpenRouter(messages:Array<{role:'system'|'user'|'assistant';content:string}>,temperature:number){const apiKey=process.env.OPENROUTER_API_KEY;if(!apiKey)throw new Error('OPENROUTER_API_KEY bulunamadı.');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);try{const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',signal:controller.signal,headers:{Authorization:`Bearer ${apiKey.trim()}`,'Content-Type':'application/json',...(process.env.APP_URL?{'HTTP-Referer':process.env.APP_URL}:{}),'X-Title':'NEXUS Kairo Studio'},body:JSON.stringify({model:process.env.OPENROUTER_MODEL||'openrouter/free',messages,temperature,max_tokens:350})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||`OpenRouter hatası: HTTP ${response.status}`);const text=extractOpenRouterText(data);if(!text)throw new Error('OpenRouter boş yanıt döndürdü.');return text}catch(e:any){if(e?.name==='AbortError')throw new Error('OpenRouter isteği zaman aşımına uğradı.');throw e}finally{clearTimeout(timeout)}}
async function generateText(systemInstruction:string,messages:Array<{role:'user'|'assistant';content:string}>,temperature:number,provider:'gemini'|'openrouter'='openrouter'){if(provider==='openrouter')return callOpenRouter([{role:'system',content:systemInstruction},...messages],temperature);if(!process.env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY bulunamadı.');const contents=messages.map(m=>({role:m.role==='assistant'?'model' as const:'user' as const,parts:[{text:m.content}]}));const response=await getGeminiClient().models.generateContent({model:'gemini-3.6-flash',contents,config:{systemInstruction}});return(response?.text||'').trim()}async function getFastRecentMemory(userId:string){const cached=memoryCache.get(userId);if(cached&&cached.expires>Date.now())return cached.items;const loader=loadRecentKdmMemory(6,userId).then(items=>{memoryCache.set(userId,{expires:Date.now()+MEMORY_TTL_MS,items});return items}).catch(()=>[]);return Promise.race([loader,sleep(700,[] as Array<{userMessage:string;reply:string}>)])}
app.get('/api/health',(_req,res)=>res.json({status:'ok',timestamp:new Date().toISOString(),geminiConfigured:Boolean(process.env.GEMINI_API_KEY),openrouterConfigured:Boolean(process.env.OPENROUTER_API_KEY),openrouterModel:process.env.OPENROUTER_MODEL||'openrouter/free'}));app.get('/api/knt/traces',async(req,res)=>{try{const userId=typeof req.query.userId==='string'?req.query.userId:'test_user_x';const traces=await loadRecentKntTraces(Number(req.query.limit||20),userId);return res.json({ok:true,userId,count:traces.length,traces})}catch(error:any){return res.status(500).json({ok:false,error:error?.message||'Trace read failed'})}});app.get('/api/language-memory',req=>{});
app.get('/api/kaira/language-memory',(req,res)=>{const userId=typeof req.query.userId==='string'?req.query.userId:'test_user_x';return res.json({ok:true,userId,...languageMemorySummary(userId)})});
const defaultDynamicState:DroitDynamicState={calmness:70,anger:10,stress:20,happiness:70,confidence:70,surprise:10,lastStatus:'Sakin ve kontrollü'};function normalizeDynamicState(value:unknown):DroitDynamicState{const s=value&&typeof value==='object'?value as Partial<DroitDynamicState>:{};const n=(v:unknown,f:number)=>{const x=typeof v==='number'?v:Number(v);return Number.isFinite(x)?x:f};return{calmness:n(s.calmness,70),anger:n(s.anger,10),stress:n(s.stress,20),happiness:n(s.happiness,70),confidence:n(s.confidence,70),surprise:n(s.surprise,10),lastStatus:typeof s.lastStatus==='string'&&s.lastStatus.trim()?s.lastStatus:'Sakin ve kontrollü',...(s.lastEvent?{lastEvent:s.lastEvent}:{}),...(s.relationship?{relationship:s.relationship}:{})}}
app.post('/api/chat',async(req,res)=>{const serverStart=now();try{const{userId='anonymous',userMessage,character,personality,behaviorProfile:baseBehaviorProfile,history=[],dynamicState=defaultDynamicState,provider='openrouter'}=req.body;if(!userMessage||typeof userMessage!=='string')return res.status(400).json({error:'userMessage is required'});const selectedProvider:'gemini'|'openrouter'=provider==='gemini'?'gemini':'openrouter',charName=character?.name||'KAIRO',charRole=character?.roleTitle||'Sunucu Yöneticisi',raceName=character?.raceName||'Sentetik Droit';const memoryStart=now();const[persistedState,persistentMemory]=await Promise.all([loadKdmState(userId).catch(()=>null),getFastRecentMemory(userId)]);const memoryMs=Math.round(now()-memoryStart),behaviorProfile=applyRelationshipContext(baseBehaviorProfile,persistedState),tone=behaviorProfile?.tone||'confident',directives=Array.isArray(behaviorProfile?.behaviorDirectives)?behaviorProfile.behaviorDirectives:[],dominantSummary=behaviorProfile?.dominantSummary||'Dengeli Droit',empathyLevel=Math.round((behaviorProfile?.empathyLevel??.5)*100),assertiveness=Math.round((behaviorProfile?.assertiveness??.5)*100),analyticalDepth=Math.round((behaviorProfile?.analyticalDepth??.5)*100);const kdmStart=now(),effectiveDynamicState=normalizeDynamicState(persistedState??dynamicState),safePersonality=(personality&&typeof personality==='object'?personality:{})as DroitPersonalityTraits,kdm=analyzeKdmInteraction(userMessage,safePersonality,effectiveDynamicState),speech=computeKairoSpeechIdentity(safePersonality,kdm.nextDynamicState,kdm.trace),validatedMemory=persistentMemory.filter(item=>validateMemoryAgainstMessage(`${item.userMessage} ${item.reply}`,userMessage).accepted),memoryContext=validatedMemory.length?validatedMemory.map((item,i)=>`#${i+1}\nKullanıcı: ${item.userMessage}\nKairo: ${item.reply}`).join('\n'):'İlgili doğrulanmış anı yok.',relationship=kdm.trace.relationship,local=tryLocalKairoReply(userMessage,safePersonality,kdm.nextDynamicState,kdm.trace,userId),kdmMs=Math.round(now()-kdmStart);
if(local.handled&&local.reply){const replyText=local.reply,consistency=validateKairoResponse(replyText,kdm.trace),timings={memoryMs,kdmMs,aiMs:0,postProcessMs:0,serverTotalMs:Math.round(now()-serverStart)};res.json({reply:replyText,providerUsed:'local_language',speechIdentity:speech,localLanguage:{intent:local.intent,confidence:local.confidence,memory:languageMemorySummary(userId)},kdm:{trace:kdm.trace,dynamicState:kdm.nextDynamicState},consistency,timings});void Promise.allSettled([saveKdmInteraction({userId,dynamicState:kdm.nextDynamicState,reasoningTrace:kdm.trace,lastUserMessage:userMessage,reply:replyText}),recordKdmMetric({userId,score:consistency.score,accepted:consistency.accepted,repaired:false,repairAttempts:0,issues:consistency.issues}),saveKntTrace({userId,userMessage,reply:replyText,reasoningTrace:kdm.trace,dynamicState:kdm.nextDynamicState,timings,providerUsed:'local_language',speechIdentity:speech})]).then(()=>memoryCache.delete(userId));return;}
const systemInstruction=`Sen NEXUS evrenindeki ${charName} adlı Droit'sun. Rol: ${charRole}. Irk: ${raceName}. Kimlik: ${dominantSummary}.\n=== KDM ===\nAmaç:${kdm.trace.messageInterpretation.intent}; duygu:${kdm.trace.messageInterpretation.sentiment}; ilişki:${relationship.warmthScore}/100; güven:${relationship.trustScore??50}; çatışma:${relationship.conflictScore??0}; kırgınlık:${relationship.hurtScore??0}; ruh hali:${kdm.trace.currentMood.moodText}; karar:${kdm.trace.decision.chosenTone}.\n${speechIdentityPrompt(speech)}\n=== HAFIZA ===\n${memoryContext}\n=== DAVRANIŞ ===\nTon:${tone}; empati:%${empathyLevel}; otorite:%${assertiveness}; analitik:%${analyticalDepth}.\n${directives.map((d:string)=>`- ${d}`).join('\n')}\nYalnızca doğal Türkçe cevabı üret.`;const messages:Array<{role:'user'|'assistant';content:string}>=[];if(Array.isArray(history))for(const item of history.slice(-8))if(item?.text&&typeof item.text==='string')messages.push({role:item.sender==='user'||item.role==='user'?'user':'assistant',content:item.text});messages.push({role:'user',content:userMessage});const aiStart=now(),replyText=await generateText(systemInstruction,messages,.65,selectedProvider),aiMs=Math.round(now()-aiStart),consistency=validateKairoResponse(replyText,kdm.trace),timings={memoryMs,kdmMs,aiMs,postProcessMs:0,serverTotalMs:Math.round(now()-serverStart)};res.json({reply:replyText,providerUsed:selectedProvider,speechIdentity:speech,kdm:{trace:kdm.trace,dynamicState:kdm.nextDynamicState},consistency,timings});void Promise.allSettled([saveKdmInteraction({userId,dynamicState:kdm.nextDynamicState,reasoningTrace:kdm.trace,lastUserMessage:userMessage,reply:replyText}),recordKdmMetric({userId,score:consistency.score,accepted:consistency.accepted,repaired:false,repairAttempts:0,issues:consistency.issues}),saveKntTrace({userId,userMessage,reply:replyText,reasoningTrace:kdm.trace,dynamicState:kdm.nextDynamicState,timings,providerUsed:selectedProvider,speechIdentity:speech})]).then(()=>memoryCache.delete(userId));return}catch(error:any){console.error('[Chat API Error]',error);if(!res.headersSent)return res.status(500).json({error:error?.message||'Chat service failed'})}});async function startServer(){const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);app.listen(PORT,()=>console.log(`NEXUS Kairo Studio running on http://localhost:${PORT}`))}startServer();
