import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createLlmSemanticUnderstandingProvider } from "./llmSemanticUnderstandingProvider";
import { projectSemanticEvent } from "./semanticInterpretationProjection";
import { SEMANTIC_INTERPRETATION_SCHEMA_VERSION } from "../types/semanticInterpretation";
const v2:any={schemaVersion:SEMANTIC_INTERPRETATION_SCHEMA_VERSION,raw:"x",normalized:"x",primaryIntent:"complaint",secondarySocialActs:[],target:"kaira",valence:"negative",severity:{disrespect:.2,coercion:0,manipulation:0,privacy:0,aggression:.25},jokingConfidence:.4,sincerityConfidence:.7,affection:.1,support:0,compliment:0,emotionalLoad:.3,apology:false,repairAttempt:false,stopRequest:false,discourseFacets:{socialRoutine:"none",discourseAct:"confusion_or_challenge",repairSignal:"clarification_request",adviceRequested:false,knowledgeQuery:null,selfMemoryQuery:null,relationalAct:"none",relationalIntensity:.2,stopQuestions:false,stopTalking:false},uncertainty:{overall:.3,intent:.2,target:.2,severity:.4},evidence:[{source:"llm",cues:["complaint"],confidence:.7}]};
describe("SemanticInterpretation@2 canonical authority",()=>{
 it("LLM producer emits v2",async()=>{const p=createLlmSemanticUnderstandingProvider({generate:async()=>JSON.stringify(v2)});const r=await p.interpret({message:"kafamı karıştırdın kankam"});expect(r.schemaVersion).toBe(SEMANTIC_INTERPRETATION_SCHEMA_VERSION);expect(r.severity.aggression).toBe(.25);expect(r.discourseFacets.repairSignal).toBe("clarification_request");});
 it("projection has no parser/regex authority",()=>{const s=readFileSync(new URL("./semanticInterpretationProjection.ts",import.meta.url),"utf8");expect(s).not.toMatch(/interpretSemanticEvent|interpretationFromRegexFloor|RegExp|\.test\(/u);});
 it("projection ignores raw wording",()=>{const neutral={...v2,primaryIntent:"smalltalk",secondarySocialActs:[],severity:{disrespect:0,coercion:0,manipulation:0,privacy:0,aggression:0}};expect(projectSemanticEvent({...neutral,raw:"aptalsın"}).insult).toBe(false);expect(projectSemanticEvent({...neutral,raw:"orospu"}).insult).toBe(false);});
 it("normal gateway rejects old incoming authority shape",()=>{const s=readFileSync(new URL("./languageUnderstandingService.ts",import.meta.url),"utf8");expect(s).not.toContain("incomingSemanticEvent");expect(s).toContain("incomingSemanticInterpretation");});
});
