import { doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../lib/firebase';

export interface LanguageMemoryProfile { wordWeights:Record<string,number>; phraseWeights:Record<string,number>; recentReplies:string[]; interactionCount:number; }
const profiles=new Map<string,LanguageMemoryProfile>();const hydrated=new Set<string>();const hydrationPromises=new Map<string,Promise<void>>();const saveTimers=new Map<string,ReturnType<typeof setTimeout>>();
const BASE_WORDS:Record<string,number>={kanka:8,ya:7,valla:5,aynen:5,he:3,iyidir:4,takılıyorum:4,senden:4};
function createProfile():LanguageMemoryProfile{return{wordWeights:{...BASE_WORDS},phraseWeights:{},recentReplies:[],interactionCount:0}}
function safeId(userId:string){return encodeURIComponent(userId||'anonymous').replace(/%/g,'_')}
function sanitize(raw:any):LanguageMemoryProfile{return{wordWeights:{...BASE_WORDS,...(raw?.wordWeights&&typeof raw.wordWeights==='object'?raw.wordWeights:{})},phraseWeights:raw?.phraseWeights&&typeof raw.phraseWeights==='object'?raw.phraseWeights:{},recentReplies:Array.isArray(raw?.recentReplies)?raw.recentReplies.filter((x:any)=>typeof x==='string').slice(0,8):[],interactionCount:Number.isFinite(Number(raw?.interactionCount))?Number(raw.interactionCount):0}}
export function getLanguageMemory(userId:string){let p=profiles.get(userId);if(!p){p=createProfile();profiles.set(userId,p)}return p}
export async function hydrateLanguageMemory(userId:string){if(hydrated.has(userId))return;const existing=hydrationPromises.get(userId);if(existing)return existing;const task=(async()=>{try{const snap=await Promise.race([getDoc(doc(db,'kairoLanguageMemory',safeId(userId))),new Promise<null>((r)=>setTimeout(()=>r(null),1500))]);if(snap&&'exists'in snap&&snap.exists())profiles.set(userId,sanitize(snap.data()))}catch(e){console.warn('[LanguageMemory] hydrate skipped',e)}finally{hydrated.add(userId);hydrationPromises.delete(userId)}})();hydrationPromises.set(userId,task);return task}
async function persist(userId:string){const p=getLanguageMemory(userId);try{await setDoc(doc(db,'kairoLanguageMemory',safeId(userId)),{...p,updatedAt:serverTimestamp()},{merge:true})}catch(e){console.warn('[LanguageMemory] persist skipped',e)}}
function schedulePersist(userId:string){const old=saveTimers.get(userId);if(old)clearTimeout(old);saveTimers.set(userId,setTimeout(()=>{saveTimers.delete(userId);void persist(userId)},500))}
export function learnLanguageReply(userId:string,reply:string){const p=getLanguageMemory(userId);p.interactionCount+=1;const normalized=reply.toLocaleLowerCase('tr-TR').replace(/[^a-zçğıöşü0-9\s:)]/gi,' ').replace(/\s+/g,' ').trim();for(const word of normalized.split(' ')){if(word.length<2)continue;p.wordWeights[word]=Math.min(30,(p.wordWeights[word]??0)+.35)}p.phraseWeights[normalized]=Math.min(20,(p.phraseWeights[normalized]??0)+1);p.recentReplies=[reply,...p.recentReplies.filter(x=>x!==reply)].slice(0,8);schedulePersist(userId)}
export function languageAffinity(userId:string,reply:string){const p=getLanguageMemory(userId),words=reply.toLocaleLowerCase('tr-TR').replace(/[^a-zçğıöşü0-9\s]/gi,' ').split(/\s+/).filter(Boolean),wordScore=words.reduce((sum,w)=>sum+(p.wordWeights[w]??0),0)/Math.max(1,words.length),phraseScore=p.phraseWeights[reply.toLocaleLowerCase('tr-TR').trim()]??0,repetitionPenalty=p.recentReplies.includes(reply)?5:0;return wordScore+phraseScore*1.5-repetitionPenalty}
export function chooseLanguageReply(userId:string,candidates:string[],seed:string){let hash=0;for(let i=0;i<seed.length;i++)hash=(hash*31+seed.charCodeAt(i))>>>0;return[...candidates].map((reply,index)=>({reply,score:languageAffinity(userId,reply)+(((hash+index*17)%100)/100)*1.25})).sort((a,b)=>b.score-a.score)[0]?.reply??candidates[0]}
export function languageMemorySummary(userId:string){const p=getLanguageMemory(userId);return{interactionCount:p.interactionCount,persistent:hydrated.has(userId),favoriteWords:Object.entries(p.wordWeights).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([word,weight])=>({word,weight:Number(weight.toFixed(2))})),recentReplies:p.recentReplies.slice(0,5)}}
