import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { deriveDiscourseState } from "./discourseStateReducer";
import { interpretSemanticEvent } from "./semanticEventEngine";
import { findKairaResponsePlanIssues, type KairaResponsePlan } from "./kairaResponsePlan";
import { buildKairaActivityPermissionChatPrompt, composeKairaActivityPermissionChatReply } from "./kairaActivityPermissionChatRuntime";
const focusedPlan = (overrides: Partial<KairaResponsePlan> = {}): KairaResponsePlan => ({ move:"repair_or_rephrase", stance:"open", register:"balanced", relationshipLevel:"new", continueConversation:true, allowQuestion:false, allowHumor:false, allowAffection:false, allowForgiveness:false, allowReopeningCloseness:false, maxSentences:1, maxWords:12, emojiBudget:0, reasons:["runtime-proof"], ...overrides });
describe("Kaira cross-layer runtime behavior proofs", () => {
  it("proves canonical promotion is structural and rollback is repository-level", () => { const responsePlan=readFileSync("src/services/kairaResponsePlan.ts","utf8"), kdm=readFileSync("src/services/kdmConsistencyEngine.ts","utf8"); expect(responsePlan).toContain('resolver: "canonical"'); expect(kdm).toContain("analyzeKdmInteractionCanonical"); expect(responsePlan).not.toContain("isCanonicalBehaviorFlagEnabled"); expect(kdm).not.toContain("isCanonicalBehaviorFlagEnabled"); });
  it.each(["iyi dedim ya amk","iyiyim be, az önce söyledim zaten","iyi işte kanka daha demin cevap verdim","iyiyim, kaç kere söyleyeyim artık"])("keeps answer-with-friction attached to Kaira's pending how-are-you question: %s", (message) => { const history=[{sender:"user",text:"naber"},{sender:"droit",text:"iyi valla sen nasılsın"}]; const event=interpretSemanticEvent(message); const state=deriveDiscourseState(history,{message,event}); expect(state.pendingQuestion?.asker).toBe("kaira"); expect(state.previousTurnDependency?.on).toBe("kaira_question"); expect(["answer","answer_with_friction","correction"]).toContain(state.previousTurnDependency?.responseKind); });
  it.each(["nasılsın sen bugün","sen bugün nasılsın","iyi misin bugün","ne yapıyorsun şimdi"])("blocks question-like acts even when the model omits a question mark: %s", (reply) => { expect(findKairaResponsePlanIssues(reply,focusedPlan())).toContain("response_plan_question_blocked"); });
  it.each(["Mert bana nasılsın diye sordu","Mert bana iyi misin diye sordu"])("does not over-block reported question content: %s", (reply) => { expect(findKairaResponsePlanIssues(reply,focusedPlan())).not.toContain("response_plan_question_blocked"); });
  it("keeps activity-permission prompts out of the planner-owned reply", () => { const prompt=buildKairaActivityPermissionChatPrompt({requestId:"req-1",activityId:"archive_exploration",activityType:"archive exploration"}); const delivered=composeKairaActivityPermissionChatReply({reply:"iyi valla",resolution:{status:"none"},prompt}); expect(delivered).toBe("iyi valla"); expect(delivered).not.toContain(prompt.text); });
  it("detects self-repeat by social act rather than exact reply text", () => { const state=deriveDiscourseState([{sender:"user",text:"naber"},{sender:"droit",text:"iyiyim, sen nasılsın"},{sender:"user",text:"iyi"},{sender:"droit",text:"bende iyi, senden naber"}]); expect(state.selfRepeat?.act).toBe("how_are_you"); expect(state.selfRepeat?.count).toBeGreaterThanOrEqual(2); });
});
