import { DroitDynamicState, DroitPersonalityTraits, ReasoningTrace } from '../types/nexus';
import { computeBehaviorProfile, BehaviorLayerProfile } from './droitBehaviorEngine';
export interface KdmAnalysisResult { trace: ReasoningTrace; behaviorProfile: BehaviorLayerProfile; nextDynamicState: DroitDynamicState; }
const clamp = (value: number, min = 0, max = 100) => Math.max(min, Math.min(max, Math.round(value)));
function classifyIntent(message: string): string { const text = message.toLowerCase(); if (/^(selam|merhaba|hey|naber|nasılsın)\b/.test(text)) return 'selamlama'; if (/(neden|nasıl|ne demek|açıkla|anlat|nedir|niye)/.test(text)) return 'bilgi_ve_aciklama'; if (/(hata|sorun|çöktü|çalışmıyor|bug|arıza|bozuk)/.test(text)) return 'sorun_cozme'; if (/(yap|oluştur|ekle|değiştir|geliştir|uygula)/.test(text)) return 'eylem_talebi'; if (/[?]/.test(text)) return 'soru'; return 'genel_sohbet'; }
function classifySentiment(message: string): string { const text = message.toLowerCase(); if (/(teşekkür|sağ ol|harika|süper|mükemmel|seviyorum|güzel|özür)/.test(text)) return 'pozitif'; if (/(sinir|kızgın|nefret|rezalet|bok|amk|lanet|berbat|aptal|salak|defol|siktir)/.test(text)) return 'negatif'; if (/(üzgün|kötü|moralim|kaygı|endişe|stres)/.test(text)) return 'duygusal_yük'; return 'nötr'; }
function warmthDeltaFor(message: string, sentiment: string): number { const text = message.toLowerCase(); let delta = sentiment === 'pozitif' ? 3 : sentiment === 'negatif' ? -2 : 0; if (/(teşekkür|sağ ol|eyvallah|kanka|kardeşim|dostum|özür)/.test(text)) delta += 2; if (/(siktir|defol|sus|aptal|salak)/.test(text)) delta -= 5; return clamp(delta, -10, 10); }
function eventKind(message: string, sentiment: string): 'positive' | 'negative' | 'neutral' { const text = message.toLowerCase(); if (/(özür|teşekkür|sağ ol|iyi ki varsın|seviyorum|harika|süper)/.test(text) || sentiment === 'pozitif') return 'positive'; if (/(aptal|salak|defol|siktir|nefret|rezalet|berbat|bok)/.test(text) || sentiment === 'negatif') return 'negative'; return 'neutral'; }
function negativePattern(message: string): string | null { const t = message.toLowerCase(); if (/(aptal|salak|gerizekalı|mal\b)/.test(t)) return 'hakaret'; if (/(siktir|defol|sus|kaybol)/.test(t)) return 'kovma_ve_reddetme'; if (/(nefret|rezalet|berbat|bok)/.test(t)) return 'aşağılama'; if (/(amk|lanet)/.test(t)) return 'agresif_dil'; return null; }
function isApology(message: string): boolean { return /(özür dilerim|özür|pardon|kusura bakma|hata ettim|yanlış yaptım)/i.test(message); }
function moodChangeFromDelta(delta: number): string { if (delta >= 4) return 'daha pozitif ve sıcak'; if (delta <= -4) return 'daha temkinli ve mesafeli'; return 'stabil'; }
const DEFAULT_DYNAMIC_STATE: DroitDynamicState = { calmness: 70, anger: 10, stress: 20, happiness: 70, confidence: 70, surprise: 10, lastStatus: 'Sakin ve kontrollü' };
export function analyzeKdmInteraction(userMessage: string, personality?: DroitPersonalityTraits | null, currentDynamicState?: DroitDynamicState | null): KdmAnalysisResult {
  const state: DroitDynamicState = { ...DEFAULT_DYNAMIC_STATE, ...(currentDynamicState || {}) }; const behaviorProfile = computeBehaviorProfile(personality || undefined, userMessage); const intent = classifyIntent(userMessage); const sentiment = classifySentiment(userMessage);
  const relationship = state.relationship || { firstSeenAt: new Date().toISOString(), lastInteractionAt: new Date().toISOString(), interactionCount: 0, familiarityDays: 0, warmth: 50, trust: 50, positiveEvents: 0, negativeEvents: 0, conflictScore: 0, hurtScore: 0, repairProgress: 0, repeatedNegativeCount: 0 };
  const calculatedDays = Number.isFinite(new Date(relationship.firstSeenAt).getTime()) ? Math.max(0, Math.floor((Date.now() - new Date(relationship.firstSeenAt).getTime()) / 86400000)) : 0; const familiarityDays = Math.max(0, relationship.familiarityDays || 0, calculatedDays); const interactionCount = Math.max(0, relationship.interactionCount || 0); const baseWarmth = clamp(relationship.warmth ?? 50); const baseTrust = clamp(relationship.trust ?? 50); const positiveEvents = Math.max(0, relationship.positiveEvents || 0); const negativeEvents = Math.max(0, relationship.negativeEvents || 0); const baseConflict = clamp(relationship.conflictScore ?? Math.min(100, negativeEvents * 4)); const baseHurt = clamp(relationship.hurtScore ?? 0); const baseRepair = clamp(relationship.repairProgress ?? 0);
  const passiveHealingDays = relationship.lastConflictAt && Number.isFinite(new Date(relationship.lastConflictAt).getTime()) ? Math.max(0, Math.floor((Date.now() - new Date(relationship.lastConflictAt).getTime()) / 86400000)) : 0; const passivelyHealedHurt = clamp(baseHurt - Math.min(15, passiveHealingDays)); const passivelyHealedConflict = clamp(baseConflict - Math.min(10, Math.floor(passiveHealingDays / 2)));
  const familiarityFactor = Math.min(familiarityDays / 30, 1); const historyQuality = clamp(50 + positiveEvents * 3 - negativeEvents * 5 - passivelyHealedConflict * 0.35 - passivelyHealedHurt * 0.25); const relationshipQuality = clamp(baseWarmth * 0.35 + baseTrust * 0.35 + historyQuality * 0.3); const toleranceMultiplier = Math.max(0.35, 1 - (0.55 * familiarityFactor * (relationshipQuality / 100)) + (passivelyHealedConflict / 100) * 0.25 + (passivelyHealedHurt / 100) * 0.2);
  const kind = eventKind(userMessage, sentiment); const apology = isApology(userMessage); const pattern = kind === 'negative' ? negativePattern(userMessage) : null; const samePattern = !!pattern && relationship.lastNegativePattern === pattern; const priorRepeatCount = Math.max(0, relationship.repeatedNegativeCount || 0); const repeatCount = pattern ? (samePattern ? priorRepeatCount + 1 : 1) : priorRepeatCount; const repeatEscalation = samePattern ? Math.min(2.2, 1 + Math.max(0, repeatCount - 1) * 0.25) : 1;
  const rawWarmthDelta = warmthDeltaFor(userMessage, sentiment); const warmthDelta = Math.round(rawWarmthDelta * toleranceMultiplier * (kind === 'negative' ? repeatEscalation : 1)); const warmthBefore = baseWarmth; const warmthAfter = clamp(warmthBefore + warmthDelta); const trustDelta = kind === 'negative' ? -4 * repeatEscalation : apology ? 1 : kind === 'positive' ? 2 : 0; const trustAfter = clamp(baseTrust + Math.round(trustDelta * toleranceMultiplier));
  let conflictAfter = passivelyHealedConflict; let hurtAfter = passivelyHealedHurt; let repairAfter = baseRepair; let lastConflictAt = relationship.lastConflictAt; let lastNegativePattern = relationship.lastNegativePattern; let lastNegativePatternAt = relationship.lastNegativePatternAt;
  if (kind === 'negative') { conflictAfter = clamp(conflictAfter + 8 * repeatEscalation); hurtAfter = clamp(hurtAfter + 12 * repeatEscalation); repairAfter = clamp(repairAfter - 8 * repeatEscalation); lastConflictAt = new Date().toISOString(); if (pattern) { lastNegativePattern = pattern; lastNegativePatternAt = lastConflictAt; } }
  else if (apology) { const apologyPower = 4 + Math.round((baseTrust / 100) * 3); conflictAfter = clamp(conflictAfter - apologyPower); hurtAfter = clamp(hurtAfter - Math.max(2, Math.round(apologyPower * 0.7))); repairAfter = clamp(repairAfter + 10); }
  else if (kind === 'positive') { conflictAfter = clamp(conflictAfter - 2); hurtAfter = clamp(hurtAfter - 1); repairAfter = clamp(repairAfter + 3); } else { conflictAfter = clamp(conflictAfter - 1); repairAfter = clamp(repairAfter + (conflictAfter > 0 ? 1 : 0)); }
  const positiveEventsAfter = positiveEvents + (kind === 'positive' ? 1 : 0); const negativeEventsAfter = negativeEvents + (kind === 'negative' ? 1 : 0); const stressDelta = Math.round((sentiment === 'negatif' ? 3 * repeatEscalation : sentiment === 'duygusal_yük' ? 2 : -1) * toleranceMultiplier); const happinessDelta = Math.round((sentiment === 'pozitif' ? 4 : sentiment === 'negatif' ? -2 * repeatEscalation : 1) * toleranceMultiplier); const confidenceDelta = intent === 'eylem_talebi' ? Math.max(1, Math.round(toleranceMultiplier)) : 0; const calmnessDelta = Math.round((sentiment === 'negatif' ? -2 * repeatEscalation : 1) * toleranceMultiplier);
  const unresolvedHurt = hurtAfter >= 20 || conflictAfter >= 25; const repeatedProblem = samePattern && repeatCount >= 2; const lastStatus = repeatedProblem ? 'Tekrarlanan davranıştan rahatsız' : apology && unresolvedHurt ? 'Yumuşuyor ama temkinli' : moodChangeFromDelta(warmthDelta);
  const nextDynamicState: DroitDynamicState = { ...state, stress: clamp((state.stress ?? 20) + stressDelta), happiness: clamp((state.happiness ?? 70) + happinessDelta), confidence: clamp((state.confidence ?? 70) + confidenceDelta), calmness: clamp((state.calmness ?? 70) + calmnessDelta), relationship: { ...relationship, familiarityDays, warmth: warmthAfter, trust: trustAfter, positiveEvents: positiveEventsAfter, negativeEvents: negativeEventsAfter, conflictScore: conflictAfter, hurtScore: hurtAfter, repairProgress: repairAfter, repeatedNegativeCount: repeatCount, ...(lastConflictAt ? { lastConflictAt } : {}), ...(lastNegativePattern ? { lastNegativePattern } : {}), ...(lastNegativePatternAt ? { lastNegativePatternAt } : {}) }, lastStatus, lastEvent: { eventTitle: repeatedProblem ? `KDM: tekrarlanan ${pattern}` : apology ? 'KDM: özür/telafi' : `KDM: ${intent}`, reactionText: `Güven %${trustAfter}; çatışma %${conflictAfter}; kırgınlık %${hurtAfter}; tekrar ${repeatCount}; etki x${repeatEscalation.toFixed(2)}.`, deltas: [{ label: 'Stres', key: 'stress', value: stressDelta }, { label: 'Mutluluk', key: 'happiness', value: happinessDelta }, { label: 'Sakinlik', key: 'calmness', value: calmnessDelta }] } };
  const trace: ReasoningTrace = { whoSent: { userName: 'Kullanıcı', isNewUser: interactionCount === 0, recognitionText: interactionCount === 0 ? 'İlk etkileşim.' : `${interactionCount} etkileşimlik tanışıklık.` }, relationship: { warmthScore: warmthAfter, warmthLabel: warmthAfter >= 70 ? 'Sıcak' : warmthAfter >= 40 ? 'Dengeli' : 'Mesafeli', note: `${familiarityDays} gün; güven %${trustAfter}; çatışma %${conflictAfter}; kırgınlık %${hurtAfter}; tekrar ${repeatCount}.`, familiarityDays, interactionCount, toleranceMultiplier, trustScore: trustAfter, conflictScore: conflictAfter, hurtScore: hurtAfter, repairProgress: repairAfter, repeatedNegativeCount: repeatCount }, currentMood: { moodText: lastStatus, reasonText: repeatedProblem ? `Aynı olumsuz davranış kalıbı (${pattern}) tekrarlandı; önceki olay hatırlandı ve tepki ağırlaştırıldı.` : apology ? 'Özür kabul edildi ancak geçmiş kırgınlık tek mesajda silinmedi.' : `Mesajın ${sentiment} sinyali ve ilişki geçmişi birlikte değerlendirildi.` }, messageInterpretation: { intent: apology ? 'özür_ve_telafi' : repeatedProblem ? 'tekrarlanan_olumsuz_davranış' : intent, sentiment, explanation: repeatedProblem ? `KDM ${pattern} kalıbını daha önceki olayla eşleştirdi; tekrar etkisi x${repeatEscalation.toFixed(2)}.` : 'KDM süre, sıcaklık, güven, çatışma, kırgınlık ve olay geçmişini birlikte değerlendirdi.' }, decision: { chosenTone: behaviorProfile.tone, explanation: repeatedProblem ? 'Tekrarlanan sınır ihlali nedeniyle tolerans düşürüldü ve tepki ağırlığı artırıldı.' : unresolvedHurt ? 'Geçmiş kırgınlık tamamen kapanmadığı için daha temkinli tepki seçildi.' : `${behaviorProfile.decisionSpeed} karar stili uygulandı.` }, memoryUpdate: { warmthBefore, warmthAfter, warmthDelta, moodChange: lastStatus, reason: repeatedProblem ? `${pattern} davranışı ${repeatCount}. kez aynı kalıpta görüldü; ilişki etkisi x${repeatEscalation.toFixed(2)} uygulandı.` : apology ? `Özür telafi sürecini ilerletti; kırgınlık ${passivelyHealedHurt}→${hurtAfter}.` : `KDM ${intent}/${sentiment} etkileşimini ilişki geçmişine dönüştürdü.` } };
  return { trace, behaviorProfile, nextDynamicState };
}
