from pathlib import Path
p=Path('server.ts')
s=p.read_text(encoding='utf-8')
s=s.replace('import { claimKairaChatRequest, completeKairaChatRequest, failKairaChatRequest } from "./src/services/kairaChatIdempotency";','import { claimCoordinatedKairaChatRequest, completeCoordinatedKairaChatRequest, failCoordinatedKairaChatRequest } from "./src/services/kairaChatIdempotencyCoordinator";')
s=s.replace('const claim = claimKairaChatRequest<any>(idempotencyKey);','const claim = await claimCoordinatedKairaChatRequest<any>(idempotencyKey);')
s=s.replace('const sendChatPayload = (payload: any) => {\n      if (idempotencyKey && ownsIdempotencyClaim) {\n        completeKairaChatRequest(idempotencyKey, payload);\n        ownsIdempotencyClaim = false;\n      }\n      return res.json(payload);\n    };','const sendChatPayload = async (payload: any) => {\n      if (idempotencyKey && ownsIdempotencyClaim) {\n        await completeCoordinatedKairaChatRequest(idempotencyKey, payload);\n        ownsIdempotencyClaim = false;\n      }\n      return res.json(payload);\n    };')
s=s.replace('      sendChatPayload({\n        sessionId,','      await sendChatPayload({\n        sessionId,',1)
s=s.replace('    sendChatPayload({\n      sessionId,','    await sendChatPayload({\n      sessionId,',1)
s=s.replace('      failKairaChatRequest(idempotencyKey, e);\n      ownsIdempotencyClaim = false;','      await failCoordinatedKairaChatRequest(idempotencyKey, e);\n      ownsIdempotencyClaim = false;')
p.write_text(s,encoding='utf-8')
