import fs from 'node:fs';

function replaceOnce(path, before, after) {
  const source = fs.readFileSync(path, 'utf8');
  if (!source.includes(before)) throw new Error(`Expected patch target not found in ${path}`);
  const next = source.replace(before, after);
  if (next === source) throw new Error(`Patch produced no change in ${path}`);
  fs.writeFileSync(path, next);
}

replaceOnce(
  'src/services/kairoResponseConsistency.ts',
  `  const emotionalContext = hasAny(\`${'${intent}'} ${'${sentiment}'}\`, [\n    /(destek|duyg|stres|yorgun|üzgün|kayg|hassas)/,\n  ]);\n  const emotionalResponse = hasAny(lower, [\n    /(anlıyorum|destek|sakin|yanınd|buraday|konuş|geçecek|zor|can sık|haklısın)/,\n  ]);`,
  `  // Generic \"duygusal_yük\" is also used for benign social routines such as\n  // greetings, so it must not by itself create a support obligation.\n  const emotionalIntent = hasAny(intent, [\n    /(destek|duygusal_paylasim|duygusal_destek|stres|yorgun|üzgün|kayg|hassas)/,\n  ]);\n  const explicitEmotionalSentiment = hasAny(sentiment, [\n    /(stres|yorgun|üzgün|kayg|hassas)/,\n  ]);\n  const emotionalContext = emotionalIntent || explicitEmotionalSentiment;\n  const emotionalResponse = hasAny(lower, [\n    /(anlıyorum|destek|sakin|yanınd|buraday|konuş|geçecek|zor|can sık|haklısın)/,\n    /^(?:(?:hmm|off)\\s+)?(?:niye|neden|ne oldu|noldu|hayırdır)(?:\\s+ya)?[?…]*$/,\n  ]);`,
);

replaceOnce(
  'src/services/kairoDialogueDecisionEngine.ts',
  `const SHORT_CONTEXTUAL_ANSWER_RE =\n  /^(?:hiç\\s*biri|hiçbiri|ikisi\\s+de|hepsi|hiçbiri\\s+değil|yok|hayır|evet|aynen|olmadı|bilmiyorum|fark\\s+etmez|sen\\s+seç|öbürü|diğeri|ilki|ikincisi)(?:\\s+(?:ya|işte|kanka))?[.!?…]*$/i;\nconst PREVIOUS_PROMPT_RE =\n  /[?？]|\\b(?:hangisi|hangisini|seç|mı|mi|mu|mü|ne dersin|sence)\\b/i;`,
  `const SHORT_CONTEXTUAL_ANSWER_RE =\n  /^(?:hiç\\s*biri|hiçbiri|ikisi\\s+de|hepsi|hiçbiri\\s+değil|yok|hayır|evet|aynen|tamam|tamamdır|peki|olur|olmadı|bilmiyorum|fark\\s+etmez|sen\\s+seç|öbürü|diğeri|ilki|ikincisi)(?:\\s+(?:ya|işte|kanka))?[.!?…]*$/i;\nconst KAIRA_SHORT_ACK_RE = /^(?:tamam|tamamdır|peki|olur|evet|aynen|hmm|he|hee)[.!?…]*$/i;\nconst PREVIOUS_CONTEXT_INVITE_RE =\n  /[?？]|\\b(?:hangisi|hangisini|seç|mı|mi|mu|mü|ne dersin|sence|istersen|ister misin|ister miydin)\\b/i;`,
);

replaceOnce(
  'src/services/kairoDialogueDecisionEngine.ts',
  `function isShortAnswerToPreviousKairaTurn(\n  history: ConversationTurn[],\n  userMessage: string,\n): boolean {\n  const previous = history.at(-1);\n  if (!previous || previous.sender !== \"droit\") return false;\n  const previousText = String(previous.text || \"\");\n  return (\n    PREVIOUS_PROMPT_RE.test(previousText) &&\n    SHORT_CONTEXTUAL_ANSWER_RE.test(userMessage.trim())\n  );\n}`,
  `function isShortAnswerToPreviousKairaTurn(\n  history: ConversationTurn[],\n  userMessage: string,\n): boolean {\n  if (!SHORT_CONTEXTUAL_ANSWER_RE.test(userMessage.trim())) return false;\n  const previous = history.at(-1);\n  if (!previous || previous.sender !== \"droit\") return false;\n  const previousText = String(previous.text || \"\");\n  if (PREVIOUS_CONTEXT_INVITE_RE.test(previousText)) return true;\n\n  // Keep a bounded acknowledgement chain attached to the last explicit prompt/offer.\n  // Example: Kaira offers more recommendations -> user \"tamam\" -> Kaira \"evet\"\n  // -> user \"evet\". The final \"evet\" must not become a fresh topic or inferred feeling.\n  if (!KAIRA_SHORT_ACK_RE.test(previousText.trim())) return false;\n  const previousUser = history.at(-2);\n  const priorKaira = history.at(-3);\n  return Boolean(\n    previousUser?.sender === \"user\" &&\n    SHORT_CONTEXTUAL_ANSWER_RE.test(String(previousUser.text || \"\").trim()) &&\n    priorKaira?.sender === \"droit\" &&\n    PREVIOUS_CONTEXT_INVITE_RE.test(String(priorKaira.text || \"\"))\n  );\n}`,
);

replaceOnce(
  'src/services/kairoDialogueDecisionEngine.ts',
  `        \"Bu kısa mesaj bağımsız bir konu değil, Kaira'nın hemen önceki sorusuna veya seçeneklerine verilen cevaptır. Yalnızca o cevaba bağlan; yeni duygu, sebep veya konu uydurma.\",`,
  `        \"Bu kısa mesaj bağımsız bir konu değil, Kaira'nın yakın önceki sorusuna, teklifine veya seçeneklerine verilen cevaptır. Yalnızca açıkça doğrulanan şeyi bağla; beğeni, duygu, sebep, tercih veya yeni konu uydurma ve yeni soru açma.\",`,
);

const testPath = 'src/services/kairaBetaConversationContinuityRegression.test.ts';
fs.writeFileSync(testPath, `import { describe, expect, it } from 'vitest';\nimport { validateKairoResponse } from './kairoResponseConsistency';\nimport { planDialogueResponse } from './kairoDialogueDecisionEngine';\n\nconst trace = (intent: string, sentiment: string, chosenTone = 'balanced') => ({\n  whoSent: { userName: 'Mert', isNewUser: false, recognitionText: 'test' },\n  relationship: {\n    warmthScore: 52,\n    warmthLabel: 'Dengeli',\n    note: 'test',\n    familiarityDays: 0,\n    interactionCount: 3,\n    toleranceMultiplier: 1,\n    trustScore: 54,\n    conflictScore: 0,\n    hurtScore: 0,\n    repairProgress: 8,\n    repeatedNegativeCount: 0,\n    conversationState: 'active',\n    repairAttempts: 0,\n  },\n  currentMood: { moodText: 'Empatik ve dikkatli', reactionMode: 'neutral', reasonText: 'test' },\n  messageInterpretation: { intent, sentiment, explanation: 'test' },\n  decision: { chosenTone, explanation: 'test' },\n  memoryUpdate: { warmthBefore: 52, warmthAfter: 52, warmthDelta: 0, moodChange: 'stabil', reason: 'test' },\n}) as any;\n\ndescribe('beta conversation continuity regressions', () => {\n  it('does not treat generic emotional-load greetings as support obligations', () => {\n    const result = validateKairoResponse('merhaba', trace('selamlama', 'duygusal_yük'));\n    expect(result.issues).not.toContain('Duygusal destek niyetiyle yanıt yeterince destekleyici değil');\n  });\n\n  it('accepts the agreed minimal curiosity response for an emotional opening', () => {\n    const result = validateKairoResponse('niye ya', trace('duygusal_paylasim', 'duygusal_yük'));\n    expect(result.issues).not.toContain('Duygusal destek niyetiyle yanıt yeterince destekleyici değil');\n    expect(result.checks.intentTone).toBe(true);\n  });\n\n  it('binds tamam to a recent explicit Kaira offer instead of creating a new topic', () => {\n    const plan = planDialogueResponse(\n      [{ sender: 'droit', text: 'bunları bi dön, sonra istersen biraz daha karışık atarım sana' } as any],\n      'tamam',\n      'Mert',\n    );\n    expect(plan).toMatchObject({ move: 'follow_previous_answer', allowFollowUpQuestion: false, allowSpeculation: false });\n  });\n\n  it('keeps a second short acknowledgement behind one Kaira ack attached to the same offer', () => {\n    const plan = planDialogueResponse(\n      [\n        { sender: 'droit', text: 'bunları bi dön, sonra istersen biraz daha karışık atarım sana' } as any,\n        { sender: 'user', participantName: 'Mert', text: 'tamam' } as any,\n        { sender: 'droit', text: 'evet' } as any,\n      ],\n      'evet',\n      'Mert',\n    );\n    expect(plan).toMatchObject({\n      move: 'follow_previous_answer',\n      allowFollowUpQuestion: false,\n      allowSpeculation: false,\n      maxSentences: 1,\n      maxWords: 8,\n    });\n    expect(plan.reason).toContain('beğeni');\n  });\n});\n`);
